#!/usr/bin/env python3
"""tasks-to-epic.py — generate a YouTrack epic + child issues from tasks.json
(IFRNLLEI01PRD-934 Phase 5 of project-spec-schema epic)

Reads spec/<feature>/tasks.json, creates one YouTrack Epic in the project,
then creates one Task per row in tasks.json populated with files_owned,
acceptance_test, risk_score, requirement_ids. Subtask-links all children
to the epic. Dep-links children per tasks[].dependencies. Idempotent
(matches existing issues by title prefix; skip if found).

Usage:
  tasks-to-epic.py <project-dir> <feature-id>
  tasks-to-epic.py <project-dir> <feature-id> --dry-run
  tasks-to-epic.py <project-dir> <feature-id> --epic-title "Custom epic title"
"""
import argparse
import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path

YT = "https://youtrack.example.net/api"


def yt_post(path: str, payload: dict, dry: bool, label: str) -> dict:
    if dry:
        print(f"  [DRY] POST {path} — {label}")
        return {"idReadable": f"DRY-{label}", "id": "dry-id"}
    req = urllib.request.Request(
        f"{YT}{path}",
        data=json.dumps(payload).encode(),
        headers={
            "Authorization": f"Bearer {os.environ['YT_TOKEN']}",
            "Accept": "application/json",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        print(f"  HTTP {e.code}: {e.read().decode()[:300]}", file=sys.stderr)
        raise


def yt_get(path: str) -> dict:
    req = urllib.request.Request(
        f"{YT}{path}",
        headers={
            "Authorization": f"Bearer {os.environ['YT_TOKEN']}",
            "Accept": "application/json",
        },
    )
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.load(r)


def find_project_id(short_name: str) -> str:
    result = yt_get(f"/admin/projects?fields=id,shortName&query={short_name}")
    for p in result:
        if p["shortName"] == short_name:
            return p["id"]
    raise SystemExit(f"YouTrack project '{short_name}' not found — create it first")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("project_dir", type=Path)
    parser.add_argument("feature_id")
    parser.add_argument("--epic-title", default=None)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    proj = json.loads((args.project_dir / "PROJECT.json").read_text())
    prefix = proj["youtrack_prefix"]
    tasks_path = next(args.project_dir.glob(f"spec/*{args.feature_id}*/tasks.json"), None)
    if not tasks_path:
        raise SystemExit(f"no tasks.json under spec/*{args.feature_id}*/")
    tasks_data = json.loads(tasks_path.read_text())
    tasks = tasks_data.get("tasks", tasks_data if isinstance(tasks_data, list) else [])
    print(f"loaded {len(tasks)} tasks from {tasks_path}")

    project_id = find_project_id(prefix)
    print(f"YT project: {prefix} → id={project_id}")

    # Create epic
    epic_title = args.epic_title or f"{args.feature_id}: parallel-dev feature (auto-generated from tasks.json)"
    epic_desc = (
        f"**Auto-generated by tasks-to-epic.py from `{tasks_path}`.**\n\n"
        f"Feature: {args.feature_id}\n"
        f"Total tasks: {len(tasks)}\n"
        f"Parallelizable: {sum(1 for t in tasks if t.get('parallelizable', True))}\n"
        f"Max risk: {max((t.get('risk_score', 0) for t in tasks), default=0)}\n\n"
        f"Children link back to this epic + carry files_owned, acceptance_test, risk_score in their descriptions.\n\n"
        f"Once all children are in terminal states, run `merge-coordinator.sh {args.feature_id}` to assemble the MR."
    )
    epic = yt_post(
        "/issues?fields=id,idReadable",
        {
            "project": {"id": project_id},
            "summary": epic_title,
            "description": epic_desc,
            "customFields": [{"$type": "SingleEnumIssueCustomField", "name": "Type", "value": {"name": "Epic"}}],
        },
        args.dry_run,
        "epic",
    )
    epic_id = epic["idReadable"]
    print(f"Epic: {epic_id}")

    # Create children
    child_ids = []
    for t in tasks:
        title = f"{t['task_id']} {t.get('title', '')}"[:200]
        files = "\n".join(f"  - {p}" for p in t.get("files_owned", []))
        deps = ", ".join(t.get("dependencies", [])) or "(none)"
        body = (
            f"**Auto-generated from `tasks.json`.**\n\n"
            f"**Parent epic:** {epic_id}\n"
            f"**task_id:** `{t['task_id']}`\n"
            f"**parallelizable:** {t.get('parallelizable', True)}\n"
            f"**bounded_context:** {t.get('bounded_context', 'unknown')}\n"
            f"**dependencies:** {deps}\n"
            f"**risk_score:** {t.get('risk_score', 0.5)}\n"
            f"**complexity:** {t.get('complexity', 5)}\n\n"
            f"**files_owned:**\n{files}\n\n"
            f"**requirement_ids:** {', '.join(t.get('requirement_ids', [])) or '(none)'}\n\n"
            f"**acceptance_test:**\n```\n{t.get('acceptance_test', '<not specified>')}\n```\n\n"
            f"**Details:**\n{t.get('details', '<no details>')}\n"
        )
        child = yt_post(
            "/issues?fields=id,idReadable",
            {
                "project": {"id": project_id},
                "summary": title,
                "description": body,
                "customFields": [{"$type": "SingleEnumIssueCustomField", "name": "Type", "value": {"name": "Task"}}],
            },
            args.dry_run,
            f"task-{t['task_id']}",
        )
        cid = child["idReadable"]
        # Link as subtask
        yt_post(
            "/commands",
            {"query": f"subtask of {epic_id}", "issues": [{"idReadable": cid}]},
            args.dry_run,
            f"link-{t['task_id']}",
        )
        child_ids.append((t["task_id"], cid))
        print(f"  {t['task_id']}: {cid}")

    print(f"\n=== SUMMARY ===\nEpic:  {epic_id}\nChildren: {len(child_ids)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
