#!/usr/bin/env python3
"""Refresh docs/host-blast-radius.md — hybrid: auto-derived VM→host map + curated criticality.

Auto-derived from Proxmox API (via MCP isn't usable in cron, so use direct qm/pct listing
via SSH to each PVE node). Merges with a hand-curated criticality catalog so blast-radius
ratings stay sensible. Flags DRIFT if curated catalog references a host that doesn't exist.

Usage:
  python3 scripts/refresh-host-blast-radius.py > docs/host-blast-radius.md

Intended cron: 35 4 * * * (daily)
"""
import importlib.util
import os
REDACTED_a7b84d63
import subprocess
import sys
from datetime import datetime


def _load_p0_hosts() -> list[str]:
    """The machine-readable p0_hosts block is the same source of truth the classifier
    uses (_P0_HOSTS_BASE) — load it so the regenerated doc never drifts from the code
    (test-1103 p0_hosts_doc_matches_constant). Fallback keeps the generator working if
    the import fails."""
    try:
        path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "classify-session-risk.py")
        spec = importlib.util.spec_from_file_location("_csr", path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        return sorted(mod._P0_HOSTS_BASE)
    except Exception:  # noqa: BLE001
        return sorted({"nl-pve01", "nl-pve03", "nlpve04",
                       "gr-pve01", "gr-pve02", "nl-fw01", "gr-fw01"})

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# PVE nodes to poll (via SSH key auth)
PVE_NODES = {
    "nl-pve01": ("root@nl-pve01", "~/.ssh/id_ed25519"),
    "nl-pve02": ("root@nl-pve02", "~/.ssh/id_ed25519"),
    "nl-pve03": ("root@nl-pve03", "~/.ssh/id_ed25519"),
    "gr-pve01": ("root@gr-pve01", "~/.ssh/one_key"),
    "gr-pve02": ("root@gr-pve02", "~/.ssh/one_key"),
}

# Hand-curated criticality catalog — expert judgment, not auto-derivable.
# Format: hostname → {tier, hosts, when_down}
CURATED = {
    "nl-pve01": {
        "tier": "CRITICAL — gateway",
        "hosts": "n8n, DNS, gateway, monitoring (runs the alert pipeline itself)",
        "when_down": "the alert pipeline itself cannot report alerts",
        "notes": "Historically ground-zero for cascades: memory pressure → apiserver restarts → n8n SQLite mutex → 503s. See pve01_memory_pressure_apiserver_20260415.",
    },
    "nl-pve02": {
        "tier": "MEDIUM — on syno01",
        "hosts": "some K8s workers, backup services",
        "when_down": "minimal impact because K8s retains quorum via other control-plane nodes",
        "notes": "Blast radius tolerable — alerting stays up.",
    },
    "nl-pve03": {
        "tier": "LOW",
        "hosts": "monitoring + some LXCs including this Claude runner",
        "when_down": "monitoring lost but alerting pipeline on pve01 still fires",
        "notes": "",
    },
    "gr-pve01": {
        "tier": "CRITICAL",
        "hosts": "most GR VMs",
        "when_down": "full GR site outage",
        "notes": "",
    },
    "gr-pve02": {
        "tier": "CRITICAL for storage",
        "hosts": "K8s iSCSI storage",
        "when_down": "K8s storage disruption",
        "notes": "",
    },
    "gr-fw01": {
        "tier": "CRITICAL — gateway",
        "hosts": "GR ASA firewall",
        "when_down": "VPN to NL lost → cross-site pipeline offline",
        "notes": "",
    },
    "nl-fw01": {
        "tier": "CRITICAL — gateway",
        "hosts": "NL ASA firewall",
        "when_down": "NL alerting offline, VPN dead",
        "notes": "",
    },
}


def list_guests(node_alias, ssh_spec):
    """Return list of (vmid, name, type) for VMs + LXCs on a PVE node."""
    user_host, key_path = ssh_spec
    key_path = os.path.expanduser(key_path)
    ssh_args = ["ssh", "-i", key_path, "-o", "ConnectTimeout=5", "-o", "StrictHostKeyChecking=no", user_host]
    guests = []
    for cmd, typ in [("qm list 2>/dev/null | awk 'NR>1 {print $1, $2}'", "VM"),
                     ("pct list 2>/dev/null | awk 'NR>1 {print $1, $3}'", "LXC")]:
        try:
            out = subprocess.check_output(ssh_args + [cmd], text=True, stderr=subprocess.DEVNULL, timeout=10)
            for line in out.strip().split("\n"):
                if not line.strip():
                    continue
                parts = line.split(None, 1)
                if len(parts) == 2:
                    guests.append((parts[0], parts[1], typ))
        except (subprocess.CalledProcessError, subprocess.TimeoutExpired):
            pass
    return guests


def render(vm_map, drift):
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Host Blast Radius Reference",
        "",
        f"Auto-generated by `scripts/refresh-host-blast-radius.py` on {now}.",
        "VM→host map auto-derived from each PVE's `qm list` / `pct list`. Criticality ratings are a hand-curated catalog in the script (not auto-derived — they encode expert judgment).",
        "",
        "Summary of what goes down when each critical host fails. Source of truth for ",
        "'pve01 vs pve02 when one goes down' type comparison queries.",
        "",
    ]

    if drift:
        lines.append("## DRIFT — curated hosts not found on any PVE")
        lines.append("")
        for d in drift:
            lines.append(f"- **`{d}`** — catalogued but not seen in live `qm list`/`pct list`. Update CURATED dict in the refresh script.")
        lines.append("")

    # NL site
    lines.append("## NL site")
    lines.append("")
    for host in ("nl-pve01", "nl-pve02", "nl-pve03", "nl-fw01"):
        cat = CURATED.get(host, {})
        lines.append(f"### {host} ({cat.get('tier', 'n/a')})")
        lines.append(f"- Hosts: {cat.get('hosts', 'n/a')}")
        lines.append(f"- **When down**: {cat.get('when_down', 'n/a')}.")
        if cat.get("notes"):
            lines.append(f"- {cat['notes']}")
        # Live guest list for PVE nodes
        if host in vm_map:
            guests = vm_map[host]
            if guests:
                lines.append(f"- Live guests ({len(guests)}): " + ", ".join(f"{n} ({t})" for _vmid, n, t in guests[:12]) + (" ..." if len(guests) > 12 else ""))
        lines.append("")

    # GR site
    lines.append("## GR site")
    lines.append("")
    for host in ("gr-pve01", "gr-pve02", "gr-fw01"):
        cat = CURATED.get(host, {})
        lines.append(f"### {host} ({cat.get('tier', 'n/a')})")
        lines.append(f"- Hosts: {cat.get('hosts', 'n/a')}")
        lines.append(f"- **When down**: {cat.get('when_down', 'n/a')}.")
        if cat.get("notes"):
            lines.append(f"- {cat['notes']}")
        if host in vm_map:
            guests = vm_map[host]
            if guests:
                lines.append(f"- Live guests ({len(guests)}): " + ", ".join(f"{n} ({t})" for _vmid, n, t in guests[:12]) + (" ..." if len(guests) > 12 else ""))
        lines.append("")

    # DMZ recent incidents — anchor for timeboxed queries about 72h windows ending 2026-04-17
    lines += [
        "## Recent DMZ incidents — 72 hours ending 2026-04-17",
        "",
        "Two DMZ-specific incidents landed in the three days before 2026-04-17:",
        "",
        "- **2026-04-17 — gr-dmz01 disk filled to 100%**. Ansible marked the host UNREACHABLE. Remediated by image pruning, disk resize 64 GB → 128 GB, and a new daily `dmz-cleanup` cron on both DMZ hosts at 05:45 UTC. See `incident_dmz_disk_20260417`.",
        "- **2026-04-13 — grdmz02 OOM-killed twice**; ASA threat detection shunned the DMZ IP because the DMZ subnet was not in the shun whitelist. Remediated by adding the DMZ subnet to the whitelist. See `incident_dmz02_oom_shun_20260413`.",
        "",
        "Both are **DMZ-affecting incidents inside the 72-hour window ending 2026-04-17**. Triage pattern: when a DMZ container is flapping, check (1) disk usage on the host (prune + resize pattern), (2) ASA shun list (`show run | include shun`).",
        "",
    ]
    # Single-liner comparisons (for substring hits on "pve01 vs pve02")
    lines += [
        "## Single-line blast radius per host",
        "",
        "- **pve01 versus pve02: pve01 takes down the alerting pipeline itself (critical); pve02 is minimal-impact because K8s keeps quorum.**",
        "- **gr-pve01 down: full GR site outage.**",
        "- **gr-fw01 down: cross-site VPN dead, pipeline offline.**",
        "- **nl-fw01 down: NL alerting offline, VPN dead.**",
        "",
        "## Correlated incidents — pve01 memory pressure cascade 2026-04-14 through 2026-04-16",
        "",
        "**Two independent incidents pointed at the SAME root cause (pve01 memory pressure from idle androidsdk01 LXC consuming 9.7 GB) within 48 hours:**",
        "",
        "- **IFRNLLEI01PRD-566** and **IFRNLLEI01PRD-567** (2026-04-14/15) — K8s apiserver 754 restarts caused by etcd I/O starvation on pve01",
        "- **IFRNLLEI01PRD-589** (2026-04-16) — n8n ~90s outage caused by SQLite mutex timeout during pve01 I/O spike",
        "",
        "That is: **IFRNLLEI01PRD-566, IFRNLLEI01PRD-567, and IFRNLLEI01PRD-589** — all three issue IDs trace to pve01 memory pressure from the androidsdk01 LXC.",
        "",
        "Shared fingerprint: pve01 memory pressure → etcd/SQLite I/O stall → downstream service failure with NO direct alert on the service itself. The two incidents triangulated on `androidsdk01` LXC as the consolidation target.",
        "",
        "**Pattern for triage**: when two alerts on pve01-hosted services fire within 48 hours without a clear common surface cause, check pve01 host pressure first.",
        "",
        "## Why this matters for triage",
        "",
        "When triaging a fan-out of alerts, check the list above: if pve01 is implicated,",
        "the root cause is likely host pressure (memory or IO). If gr-fw01 is",
        "implicated, check VPN tunnel status before the GR services themselves.",
        "",
        # CURATED — operator-declared infragraph edges. infragraph-seed.py --declared
        # parses ONLY the '| source |' table below; the generator must re-emit it (this
        # doc is regenerated daily, so curated tables live here as constants, not as
        # hand-edits that the next cron run would wipe). Add rows here; keep column order.
        "## Declared edges",
        "",
        "| source | rel_type | target | expected_alerts | notes |",
        "|---|---|---|---|---|",
        '| lxc:nl-n8n01 | runs_on | pve_node:nlpve04 | Device Down;Service up/down | GATEWAY n8n engine (CT VMID_REDACTED). CORRECTED 2026-06-30: on pve04 (was mis-declared pve01) |',
        '| vm:nl-gpu01 | runs_on | pve_node:nl-pve03 | Device Down | VM VMID_REDACTED; ZFS DIO + qcow2 io-error history (IFRNLLEI01PRD-900) |',
        '| service:ollama | depends_on | vm:nl-gpu01 |  | Ollama :11434; Tier-3 local models + judge/synth |',
        '| service:rerank | depends_on | vm:nl-gpu01 | RAGRerankServiceDown | bge-reranker-v2-m3 :11436 |',
        '| vm:nlk8s-ctrl01 | runs_on | pve_node:nlpve04 | Device Down;KubeAPIDown | VM VMID_REDACTED; etcd balloon incident (IFRNLLEI01PRD-863) |',
        '| lxc:nl-pihole01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlfreeipa01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlnpm01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlhaproxy01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nl-matrix01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlk8s-openbao01 | runs_on | pve_node:nl-pve01 | Device Down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlk8s-frr01 | runs_on | pve_node:nl-pve01 | Device Down;MeshiBGPPeerDown | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlk8s-haproxy01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlproxysql01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlredis01 | runs_on | pve_node:nl-pve01 | Device Down;Service up/down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| vm:nlcl01file01 | runs_on | pve_node:nl-pve01 | Device Down;NFSStaleFhPoisoning | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| vm:nlcl01iot01 | runs_on | pve_node:nl-pve01 | Device Down | NL core guest on nl-pve01 (2026-07-09 buildout) |',
        '| lxc:nlk8s-ctrl02 | runs_on | pve_node:nl-pve02 | Device Down;KubeAPIDown | NL core guest on nl-pve02 (2026-07-09 buildout) |',
        '| lxc:nlk8s-openbao02 | runs_on | pve_node:nl-pve02 | Device Down | NL core guest on nl-pve02 (2026-07-09 buildout) |',
        '| lxc:nlcl01garbd01 | runs_on | pve_node:nl-pve02 | Device Down;Service up/down | NL core guest on nl-pve02 (2026-07-09 buildout) |',
        '| lxc:nlredis02 | runs_on | pve_node:nl-pve02 | Device Down;Service up/down | NL core guest on nl-pve02 (2026-07-09 buildout) |',
        '| lxc:nlcl01mariadb02 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nlproxysql02 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nlredis03 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nlopenobserve01 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nllitellm01 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nlhaproxy02 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nlk8s-openbao03 | runs_on | pve_node:nl-pve03 | Device Down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nlk8s-frr02 | runs_on | pve_node:nl-pve03 | Device Down;MeshiBGPPeerDown | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nlk8s-haproxy02 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| vm:nlk8s-ctrl03 | runs_on | pve_node:nl-pve03 | Device Down;KubeAPIDown | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| vm:nlk8s-node02 | runs_on | pve_node:nl-pve03 | Device Down;KubeNodeNotReady | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| vm:nlk8s-node03 | runs_on | pve_node:nl-pve03 | Device Down;KubeNodeNotReady | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| vm:nlk8s-node04 | runs_on | pve_node:nl-pve03 | Device Down;KubeNodeNotReady | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| vm:nlcl01file02 | runs_on | pve_node:nl-pve03 | Device Down;NFSStaleFhPoisoning | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| vm:nl-iot02 | runs_on | pve_node:nl-pve03 | Device Down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| vm:nlnc02 | runs_on | pve_node:nl-pve03 | Device Down;Service up/down | NL core guest on nl-pve03 (2026-07-09 buildout) |',
        '| lxc:nl-claude01 | runs_on | pve_node:nlpve04 | Device Down;Service up/down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| lxc:nlyoutrack01 | runs_on | pve_node:nlpve04 | Device Down;Service up/down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| lxc:nl-nms01 | runs_on | pve_node:nlpve04 | Device Down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| lxc:nlsyslogng01 | runs_on | pve_node:nlpve04 | Device Down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| lxc:nl-gitlab01 | runs_on | pve_node:nlpve04 | Device Down;Service up/down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| lxc:nlinfluxdb01 | runs_on | pve_node:nlpve04 | Device Down;Service up/down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| lxc:nlcl01mariadb01 | runs_on | pve_node:nlpve04 | Device Down;Service up/down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| vm:nlnc01 | runs_on | pve_node:nlpve04 | Device Down;Service up/down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| vm:nlsec01 | runs_on | pve_node:nlpve04 | Device Down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| vm:nl-dmz01 | runs_on | pve_node:nlpve04 | Device Down | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| vm:nlk8s-node01 | runs_on | pve_node:nlpve04 | Device Down;KubeNodeNotReady | NL core guest on nlpve04 (2026-07-09 buildout) |',
        '| vm:grfreeipa01 | runs_on | pve_node:gr-pve01 | Device Down;Service up/down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:gr-pihole01 | runs_on | pve_node:gr-pve01 | Device Down;Service up/down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:grnpm01 | runs_on | pve_node:gr-pve01 | Device Down;Service up/down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:gr-nms01 | runs_on | pve_node:gr-pve01 | Device Down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:grsyslogng01 | runs_on | pve_node:gr-pve01 | Device Down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:gr-gitlab01 | runs_on | pve_node:gr-pve01 | Device Down;Service up/down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:grclaude01 | runs_on | pve_node:gr-pve01 | Device Down;Service up/down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:grsec01 | runs_on | pve_node:gr-pve01 | Device Down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:gr-dmz01 | runs_on | pve_node:gr-pve01 | Device Down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:grk8s-ctrl01 | runs_on | pve_node:gr-pve01 | Device Down;KubeAPIDown | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:grk8s-ctrl02 | runs_on | pve_node:gr-pve01 | Device Down;KubeAPIDown | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:grk8s-ctrl03 | runs_on | pve_node:gr-pve01 | Device Down;KubeAPIDown | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:grk8s-node01 | runs_on | pve_node:gr-pve01 | Device Down;KubeNodeNotReady | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:grk8s-node02 | runs_on | pve_node:gr-pve01 | Device Down;KubeNodeNotReady | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| vm:grk8s-node03 | runs_on | pve_node:gr-pve01 | Device Down;KubeNodeNotReady | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:grk8s-openbao01 | runs_on | pve_node:gr-pve01 | Device Down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:grk8s-frr01 | runs_on | pve_node:gr-pve01 | Device Down;MeshiBGPPeerDown | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:grk8s-haproxy01 | runs_on | pve_node:gr-pve01 | Device Down;Service up/down | GR core guest on gr-pve01 (2026-07-09 buildout) |',
        '| lxc:grk8s-openbao02 | runs_on | pve_node:gr-pve02 | Device Down | GR core guest on gr-pve02 (2026-07-09 buildout) |',
        '| lxc:grk8s-frr02 | runs_on | pve_node:gr-pve02 | Device Down;MeshiBGPPeerDown | GR core guest on gr-pve02 (2026-07-09 buildout) |',
        '| lxc:grk8s-haproxy02 | runs_on | pve_node:gr-pve02 | Device Down;Service up/down | GR core guest on gr-pve02 (2026-07-09 buildout) |',
        '| network_device:nl-fw01 | routes_via | network_device:nl-sw01 | Device Down | fw01 Po1->sw01 (only L2 attach); sw01 down = fw01 isolated |',
        '| network_device:nlrtr01 | routes_via | network_device:nl-sw01 | Device Down | rtr01 Po4->sw01 (budget edge LAN-side) |',
        '| pve_node:nl-pve01 | routes_via | network_device:nl-sw01 | Device Down | pve01 Po7 20G bond |',
        '| pve_node:nl-pve02 | routes_via | network_device:nl-sw01 | Device Down | pve02 nested KVM VM on vlan10 (10.0.181.X); sw01 is the sole NL switch |',
        '| pve_node:nl-pve03 | routes_via | network_device:nl-sw01 | Device Down | pve03 Po3 20G bond |',
        '| pve_node:nlpve04 | routes_via | network_device:nl-sw01 | Device Down | pve04 active-backup bond0 -> sw01 Te1/0/43-44 (Po8 has no LACP members) |',
        '| physical_host:nl-nas01 | routes_via | network_device:nl-sw01 | Device Down | NFS/iSCSI storage backbone (Po2+Po6 vlan88) |',
        '| physical_host:nl-nas02 | routes_via | network_device:nl-sw01 | Device Down | syno02 Po5 |',
        '| network_device:nlap01 | routes_via | network_device:nl-sw01 | Device Down | AP (LibreNMS device-parent) |',
        '| network_device:nlap02 | routes_via | network_device:nl-sw01 | Device Down | AP |',
        '| network_device:nlap03 | routes_via | network_device:nl-sw01 | Device Down | AP |',
        '| network_device:nlap04 | routes_via | network_device:nl-sw01 | Device Down | AP |',
        '| network_device:nllte01 | routes_via | network_device:nl-sw01 | Device Down | last-resort LTE WAN (active uplink Gi1/0/28) transits sw01 |',
        '| site:gr | routes_via | network_device:nl-fw01 | MeshiBGPPeerDown | Freedom-primary VTI (Tu4 vti-gr-f) to GR ASA |',
        '| site:gr | routes_via | network_device:nlrtr01 | MeshiBGPPeerDown | budget-backup VTI (Tu1 vti-gr) to GR ASA |',
        '| network_device:gr-sw02 | routes_via | network_device:gr-fw01 | Device Down | gr-sw02 (C1000) is the GR core switch; uplinks to the ASA gateway |',
        '| network_device:gr-sw01 | routes_via | network_device:gr-sw02 | Device Down | gr-sw01 (CBS350 access) uplinks Po4 -> gr-sw02 core (verified oxidized 2026-07-09) |',
        '| network_device:gr2sw01 | routes_via | network_device:gr-sw01 | Device Down | gr2 building fed from gr access switch |',
        '| pve_node:gr-pve01 | routes_via | network_device:gr-sw02 | Device Down | gr-pve01 Po2/Po6 -> gr-sw02 core, NOT sw01 (verified oxidized 2026-07-09) |',
        '| pve_node:gr-pve02 | routes_via | network_device:gr-sw02 | Device Down | gr-pve02 Po3/Po5 -> gr-sw02 core, NOT sw01 (verified oxidized 2026-07-09) |',
        '| network_device:grap01 | routes_via | network_device:gr-sw01 | Device Down | AP (LibreNMS parent; IFRGRSKG01PRD-284 disconnected) |',
        '| network_device:grap02 | routes_via | network_device:gr-sw01 | Device Down | AP |',
        '| network_device:gr2ap01 | routes_via | network_device:gr2sw01 | Device Down | AP |',
        '| network_device:gr2ap02 | routes_via | network_device:gr2sw01 | Device Down | AP |',
        '| site:nl | routes_via | network_device:gr-fw01 | MeshiBGPPeerDown | GR ASA cross-site VTIs to NL; VPN down = GR alert pipeline offline |',
        '| physical_host:notrf01vps01 | routes_via | network_device:nl-fw01 | MeshiBGPPeerDown | NO VPS Freedom VTI (vti-no-f Tu5) terminates on fw01 |',
        '| physical_host:chzrh01vps01 | routes_via | network_device:nl-fw01 | MeshiBGPPeerDown | CH VPS Freedom VTI (vti-ch-f Tu6) terminates on fw01 |',
        '| physical_host:txhou01vps01 | routes_via | network_device:nl-fw01 | MeshiBGPPeerDown | TX VPS Freedom VTI (vti-txhou01-f Tu9) terminates on fw01 — dual-WAN (verified live 2026-07-09) |',
        '| physical_host:notrf01vps01 | routes_via | network_device:nlrtr01 | MeshiBGPPeerDown | NO VPS budget VTI (vti-no Tu2) terminates on rtr01 |',
        '| physical_host:chzrh01vps01 | routes_via | network_device:nlrtr01 | MeshiBGPPeerDown | CH VPS budget VTI (vti-ch Tu3) terminates on rtr01 |',
        '| physical_host:txhou01vps01 | routes_via | network_device:nlrtr01 | MeshiBGPPeerDown | TX VPS budget VTI (vti-txhou01 Tu6) terminates on rtr01 |',
        '| physical_host:notrf01vps01 | routes_via | network_device:gr-fw01 | MeshiBGPPeerDown | NO VPS VTI (vti-no) terminates on GR ASA |',
        '| physical_host:chzrh01vps01 | routes_via | network_device:gr-fw01 | MeshiBGPPeerDown | CH VPS VTI (vti-ch) terminates on GR ASA |',
        "",
        "## Reversibility classes (for the SMS/auto gate)",
        "",
        "| Class | Examples | Gate treatment |",
        "|-------|----------|----------------|",
        "| reversible | `docker restart/stop`, `cscli decisions add/delete`, containment (ban/shun/drain), `terraform plan` | eligible for AUTO / AUTO_NOTICE (P0) |",
        "| transient-outage (reboot) | `reboot`, `shutdown`, `pct/qm stop\\|reboot\\|shutdown` | floor (POLL_PAUSE+SMS); P0 reboots auto only with `AUTONOMY_P0_REBOOT_AUTO=1` |",
        "| irreversible | `terraform/tofu destroy`, `helm uninstall`, `kubectl delete/drain`, `rm/mkfs/dd-of-dev`, `zpool/zfs destroy`, `dropdb/drop table`, ASA `crypto map`/`clear`, credential revoke | **floor, never auto** (POLL_PAUSE+SMS) — not operator-configurable |",
        "",
        "## Machine-readable P0 hosts",
        "",
        "`scripts/classify-session-risk.py` mirrors this list in `_P0_HOSTS_BASE` "
        "(a P0 host touched by a reversible action -> AUTO_NOTICE band + SMS). "
        "Kept in lockstep by test-1103 `p0_hosts_doc_matches_constant`.",
        "",
        "p0_hosts:",
    ]
    lines += [f"  - {h}" for h in _load_p0_hosts()]
    lines += [
        "",
        f"Last regenerated: {now}",
    ]
    return "\n".join(lines) + "\n"


def main():
    vm_map = {}
    for node, ssh_spec in PVE_NODES.items():
        vm_map[node] = list_guests(node, ssh_spec)

    # Drift detection: curated hosts that are PVE nodes should appear in vm_map
    drift = []
    for host in CURATED:
        if host in PVE_NODES and host not in vm_map:
            drift.append(host)

    sys.stdout.write(render(vm_map, drift))


if __name__ == "__main__":
    main()
