#!/usr/bin/env python3
"""Auto-regenerate docs/rag-metrics-reference.md from source.

Scrapes `kb_*` Prometheus metric names + HELP descriptions from:
  - scripts/kb-latency-probe.py        (primary emitter)
  - scripts/weekly-eval-cron.sh        (eval metrics)
  - prometheus/alert-rules/rag-health.yml (alert references)

Every `# HELP kb_xxx ...` line paired with a nearby `# TYPE kb_xxx ...` is recorded.

Usage:
  python3 scripts/refresh-rag-metrics-reference.py > docs/rag-metrics-reference.md

Intended cron: 25 4 * * *
"""
import os
REDACTED_a7b84d63
import sys
from datetime import datetime

import yaml

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SOURCES = [
    os.path.join(REPO, "scripts/kb-latency-probe.py"),
    os.path.join(REPO, "scripts/weekly-eval-cron.sh"),
]
ALERTS = os.path.join(REPO, "prometheus/alert-rules/rag-health.yml")


def extract_metrics():
    """Scan sources for HELP/TYPE/metric-name triples."""
    metrics = {}  # name -> {help, type, source}
    help_re = re.compile(r'# HELP (\w+) (.+)')
    type_re = re.compile(r'# TYPE (\w+) (\w+)')

    def clean(s):
        # Strip trailing quote tokens, commas, trailing backslashes from Python/shell contexts
        return s.strip().rstrip('"').rstrip("'").rstrip(",").rstrip('")').rstrip("')").rstrip()

    for src in SOURCES:
        if not os.path.exists(src):
            continue
        with open(src) as f:
            for line in f:
                # Search inside the line (handles Python echo "# HELP ..." and shell echo)
                hm = help_re.search(line)
                if hm:
                    name = hm.group(1)
                    desc = clean(hm.group(2))
                    if name.startswith("kb_"):
                        metrics.setdefault(name, {})["help"] = desc
                        metrics[name].setdefault("source", os.path.basename(src))
                tm = type_re.search(line)
                if tm:
                    name = tm.group(1)
                    ty = clean(tm.group(2))
                    if name.startswith("kb_"):
                        metrics.setdefault(name, {})["type"] = ty
    return metrics


def extract_alerts():
    """Return list of {name, expr, summary} parsed from rag-health.yml.

    Uses PyYAML instead of line-based regex so multi-line expressions
    (`expr: |`) and unquoted scalars parse correctly.
    """
    if not os.path.exists(ALERTS):
        return []
    with open(ALERTS) as f:
        data = yaml.safe_load(f) or {}
    alerts = []
    for group in data.get("groups", []) or []:
        for rule in group.get("rules", []) or []:
            name = rule.get("alert")
            if not name:
                continue
            expr = rule.get("expr", "")
            if isinstance(expr, str):
                expr = expr.strip()
            annotations = rule.get("annotations") or {}
            summary = (annotations.get("summary") or "").strip()
            alerts.append({"name": name, "expr": expr, "summary": summary})
    return alerts


def render(metrics, alerts):
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# RAG Pipeline — Prometheus Metrics Reference",
        "",
        f"Auto-generated by `scripts/refresh-rag-metrics-reference.py` on {now}.",
        f"Source: `kb-latency-probe.py` (cron `*/5 * * * *`) → `/var/lib/node_exporter/textfile_collector/kb_rag.prom`.",
        "",
        "## All metrics",
        "",
        "| Metric | Type | Description | Source |",
        "|---|---|---|---|",
    ]
    for name in sorted(metrics):
        m = metrics[name]
        lines.append(
            f"| `{name}` | {m.get('type', '?')} | {m.get('help', '—')} | {m.get('source', '?')} |"
        )
    lines += [
        "",
        "## Current alert rules (from `prometheus/alert-rules/rag-health.yml`)",
        "",
        "| Alert | Expression | Summary |",
        "|---|---|---|",
    ]
    for a in alerts:
        lines.append(f"| `{a.get('name','?')}` | `{a.get('expr','?')}` | {a.get('summary','—')} |")
    lines += [
        "",
        "## One-line reference",
        "",
        "- Retrieval latency quantiles: `kb_retrieval_latency_seconds{quantile}`",
        "- Rerank service health: `kb_rerank_service_up` (1=up, 0=down)",
        "- Rerank probe latency: `kb_rerank_probe_latency_ms`",
        "- Corpus size: `kb_embedded_rows{table}` and `kb_embedded_rows_total`",
        "- Migration trigger: `kb_migration_trigger_distance` (≥1.0 = migrate)",
        "- Silent qwen_json failures: `kb_qwen_json_failure_total`",
        "- Weekly eval metrics: `kb_hard_eval_hit_rate`, `kb_hard_eval_coverage_rate`, `kb_hard_eval_kg_coverage`",
        "",
        "## Where to find",
        "",
        "- Live file: `/var/lib/node_exporter/textfile_collector/kb_rag.prom` on `nl-claude01`",
        "- Grafana dashboard: `grafana/rag-observability.json` (10 panels)",
        "- Probe source: `scripts/kb-latency-probe.py`",
        "- Alert rules: `prometheus/alert-rules/rag-health.yml`",
        "",
        f"Last regenerated: {now}",
    ]
    return "\n".join(lines) + "\n"


def main():
    metrics = extract_metrics()
    alerts = extract_alerts()
    sys.stdout.write(render(metrics, alerts))


if __name__ == "__main__":
    main()
