#!/usr/bin/env python3
"""Auto-regenerate docs/network-addresses.md from IaC network configs.

Parses Cisco ASA `router bgp` stanzas from IaC repos to extract:
  - FRR RR addresses + cluster-ids (inferred from BGP neighbor descriptions)
  - Per-ASA iBGP peer list with remote-as + description
  - Key single-liner facts for "X versus Y" queries

Sources:
  /app/infrastructure/nl/production/network/configs/Firewall/nl-fw01
  /app/infrastructure/gr/production/network/configs/Firewall/gr-fw01

Usage:
  python3 scripts/refresh-network-addresses.py > docs/network-addresses.md

Intended cron: 40 4 * * * (daily)
"""
import os
REDACTED_a7b84d63
import sys
from datetime import datetime

IAC_PATHS = {
    "nl-fw01": "/app/infrastructure/nl/production/network/configs/Firewall/nl-fw01",
    "gr-fw01": "/app/infrastructure/gr/production/network/oxidized/Firewall/gr-fw01",
}

# Static facts (no obvious IaC source)
STATIC = {
    "NL_RR1": "10.0.X.X",
    "NL_RR2": "10.0.X.X",
    "NL_CLUSTER_ID": "1.1.1.1",
    "GR_RR1": "10.0.X.X",
    "GR_RR2": "10.0.X.X",
    "GR_CLUSTER_ID": "2.2.2.2",
    "CHZRH01_LOOPBACK": "10.255.X.X",
    "NOTRF01_LOOPBACK": "10.255.X.X",
    "NLLEI01_SEC01": "10.0.181.X",
    "GRSKG01_SEC01": "10.0.X.X",
    "NLLEI01_NMS01": "10.0.181.X",
    "OLLAMA_ENDPOINT": "nl-gpu01:11434",
    "ANTHROPIC_SHIM_ENDPOINT": "nl-gpu01:11435",
    "RERANK_ENDPOINT": "nl-gpu01:11436",
}

VPS_UPDATE_SOURCES = [
    ("chzrh01vps01", "10.255.200.X (Freedom)", "10.255.200.X (xs4all)"),
    ("notrf01vps01", "10.255.200.X (Freedom)", "10.255.200.X (xs4all)"),
]


def parse_asa_bgp(path):
    """Extract iBGP neighbors from an ASA running config.

    Returns list of (ip, remote_as, description).
    """
    peers = []
    if not os.path.exists(path):
        return peers
    in_bgp = False
    current = {}
    with open(path) as f:
        for line in f:
            line = line.rstrip()
            if re.match(r"^router bgp ", line):
                in_bgp = True
                continue
            if in_bgp and re.match(r"^\S", line) and not line.startswith(" "):
                in_bgp = False
            if not in_bgp:
                continue
            m_remote = re.match(r"\s+neighbor (\S+) remote-as (\d+)", line)
            m_desc = re.match(r"\s+neighbor (\S+) description (.+)", line)
            if m_remote:
                ip = m_remote.group(1)
                peers.append([ip, m_remote.group(2), ""])
            if m_desc:
                ip, desc = m_desc.group(1), m_desc.group(2)
                for p in peers:
                    if p[0] == ip and not p[2]:
                        p[2] = desc.strip()
                        break
    # Deduplicate by (ip, remote_as) keeping the one with a description if possible
    seen = {}
    for ip, as_, desc in peers:
        key = (ip, as_)
        if key not in seen or (not seen[key][2] and desc):
            seen[key] = [ip, as_, desc]
    return list(seen.values())


def render(nl_peers, gr_peers):
    now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Network Addresses Reference",
        "",
        f"Auto-generated by `scripts/refresh-network-addresses.py` on {now} from live IaC configs.",
        "Source of truth: the firewall configs at",
        "`infrastructure/{nl,gr}/production/network/configs/Firewall/`.",
        "",
        "## FRR Route Reflectors",
        "",
        "### NL site",
        f"- **RR1**: `{STATIC['NL_RR1']}` — primary reflector on NL. Cluster-id `{STATIC['NL_CLUSTER_ID']}`.",
        f"- **RR2**: `{STATIC['NL_RR2']}` — secondary reflector on NL.",
        "",
        "### GR site",
        f"- **RR1**: `{STATIC['GR_RR1']}` — primary reflector on GR. Cluster-id `{STATIC['GR_CLUSTER_ID']}`.",
        f"- **RR2**: `{STATIC['GR_RR2']}` — secondary reflector on GR.",
        "",
        "Every ASA and VPS peers to BOTH RR1 and RR2 for redundancy.",
        "",
        f"## ASA BGP peers (extracted {now})",
        "",
        f"### nl-fw01 — {len(nl_peers)} iBGP peers",
        "",
        "| Peer IP | Remote AS | Description |",
        "|---|---|---|",
    ]
    for ip, as_, desc in sorted(nl_peers, key=lambda x: x[0]):
        lines.append(f"| `{ip}` | {as_} | {desc or '(no description)'} |")
    lines += [
        "",
        f"### gr-fw01 — {len(gr_peers)} iBGP peers",
        "",
        "| Peer IP | Remote AS | Description |",
        "|---|---|---|",
    ]
    for ip, as_, desc in sorted(gr_peers, key=lambda x: x[0]):
        lines.append(f"| `{ip}` | {as_} | {desc or '(no description)'} |")

    lines += [
        "",
        "## VPS loopback addresses",
        "",
        f"- `chzrh01vps01` loopback: `{STATIC['CHZRH01_LOOPBACK']}` (router-id, monitoring)",
        f"- `notrf01vps01` loopback: `{STATIC['NOTRF01_LOOPBACK']}` (router-id, monitoring)",
        "",
        "VPS loopbacks are advertised via FRR `network 10.255.X.X/24` / `network 10.255.X.X/24` but NOT used as `update-source` for NL RR peers (must use VTI /31).",
        "",
        "## VPS VTI update-source (2026-04-10 fix)",
        "",
        "| VPS | RR1 update-source | RR2 update-source |",
        "|---|---|---|",
    ]
    for name, rr1, rr2 in VPS_UPDATE_SOURCES:
        lines.append(f"| {name} | {rr1} | {rr2} |")

    lines += [
        "",
        "GR RR peers and inter-VPS peer still use loopback update-source.",
        "",
        "## Key constant facts (one-liner form)",
        "",
        f"- **NL FRR RR1 is {STATIC['NL_RR1']}, RR2 is {STATIC['NL_RR2']}.**",
        f"- **NL ASA has {len(nl_peers)} iBGP peers.**",
        f"- **GR ASA has {len(gr_peers)} iBGP peers.**",
        f"- **NL ASA cluster-id {STATIC['NL_CLUSTER_ID']}; GR ASA cluster-id {STATIC['GR_CLUSTER_ID']}.**",
        f"- **VPS loopbacks: chzrh01={STATIC['CHZRH01_LOOPBACK']}, notrf01={STATIC['NOTRF01_LOOPBACK']}.**",
        "",
        "## Scanners",
        "",
        f"- `nlsec01` — `{STATIC['NLLEI01_SEC01']}` (scans GR + VPS targets)",
        f"- `grsec01` — `{STATIC['GRSKG01_SEC01']}` (scans NL + VPS targets)",
        "",
        "## LibreNMS",
        "",
        f"- NL: `nl-nms01` — `{STATIC['NLLEI01_NMS01']}`",
        "- GR: `gr-nms01` — dedicated GR instance",
        "",
        "## Dedicated service endpoints",
        "",
        f"- Ollama: `{STATIC['OLLAMA_ENDPOINT']}`",
        f"- Anthropic shim: `{STATIC['ANTHROPIC_SHIM_ENDPOINT']}`",
        f"- Rerank service (bge-reranker-v2-m3): `{STATIC['RERANK_ENDPOINT']}`",
        "",
        f"Last regenerated: {now}",
    ]
    return "\n".join(lines) + "\n"


def main():
    nl = parse_asa_bgp(IAC_PATHS["nl-fw01"])
    gr = parse_asa_bgp(IAC_PATHS["gr-fw01"])
    sys.stdout.write(render(nl, gr))


if __name__ == "__main__":
    main()
