#!/usr/bin/env python3
"""Auto-render the skill/agent/command index from .claude/**/*.md frontmatter.

Reads:
  .claude/agents/*.md       (sub-agents)
  .claude/skills/*/SKILL.md (skills)
  .claude/commands/*.md     (commands)

Emits:
  A single markdown file (stdout or path from argv[1]) with three grouped
  tables (agents, skills, commands) listing name, description, version,
  requires.bins, requires.env, model, and file path. Output is deterministic
  (sorted by kind then name) so test-656-skill-index-fresh.sh can diff it
  against the committed docs/skills-index.md.

Usage:
  scripts/render-skill-index.py              # stdout
  scripts/render-skill-index.py docs/skills-index.md

Scorecard rationale (IFRNLLEI01PRD-715):
- Closes 'Skill discoverability / index' (2->5) and 'Governance / versioning' (2->4).
- Pattern from /tmp/agents-cli/docs/hooks/skills_reference.py.
"""
import sys
import pathlib
import yaml
from typing import Dict, List, Tuple

ROOT = pathlib.Path(__file__).resolve().parent.parent
AGENTS_DIR = ROOT / ".claude" / "agents"
SKILLS_DIR = ROOT / ".claude" / "skills"
COMMANDS_DIR = ROOT / ".claude" / "commands"


def parse_frontmatter(path: pathlib.Path):
    """Return frontmatter dict, or None if the file has no YAML frontmatter.

    Unlabeled .md files (e.g. `.claude/commands/review.md` which is plain
    prose) are silently skipped — they are not part of the indexable
    surface.
    """
    text = path.read_text()
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end < 0:
        return None
    try:
        fm = yaml.safe_load(text[4:end])
    except yaml.YAMLError as e:
        raise ValueError(f"{path}: invalid YAML — {e}")
    if not isinstance(fm, dict):
        return None
    return fm


def collect() -> List[Tuple[str, str, Dict, pathlib.Path]]:
    """Returns list of (kind, name, frontmatter, path), sorted (kind, name)."""
    entries: List[Tuple[str, str, Dict, pathlib.Path]] = []
    for path in sorted(AGENTS_DIR.glob("*.md")):
        fm = parse_frontmatter(path)
        if fm is None:
            continue
        entries.append(("agent", fm.get("name", path.stem), fm, path))
    for sub in sorted(SKILLS_DIR.glob("*/")):
        skill_md = sub / "SKILL.md"
        if not skill_md.exists():
            continue
        fm = parse_frontmatter(skill_md)
        if fm is None:
            continue
        entries.append(("skill", fm.get("name", sub.name), fm, skill_md))
    if COMMANDS_DIR.exists():
        for path in sorted(COMMANDS_DIR.glob("*.md")):
            fm = parse_frontmatter(path)
            if fm is None:
                continue
            entries.append(("command", fm.get("name", path.stem), fm, path))
    entries.sort(key=lambda t: (t[0], t[1]))
    return entries


def flatten_desc(desc) -> str:
    """Normalise description: strip newlines, collapse whitespace, limit length."""
    if desc is None:
        return ""
    s = " ".join(str(desc).split())
    return s


def fmt_requires(req) -> str:
    if not isinstance(req, dict):
        return "-"
    bins = req.get("bins") or []
    env = req.get("env") or []
    parts = []
    if bins:
        parts.append("bins: " + ", ".join(bins))
    if env:
        parts.append("env: " + ", ".join(env))
    return "; ".join(parts) if parts else "(none)"


def render(entries) -> str:
    lines: List[str] = []
    lines.append("# Claude Gateway skill / agent / command index")
    lines.append("")
    lines.append("> Auto-generated by `scripts/render-skill-index.py` from")
    lines.append("> `.claude/{agents,skills,commands}/**/*.md` frontmatter.")
    lines.append("> Do not edit by hand — the drift test")
    lines.append("> (`scripts/qa/suites/test-656-skill-index-fresh.sh`) will fail")
    lines.append("> on any divergence. Re-render with:")
    lines.append("> ")
    lines.append("> ```")
    lines.append("> python3 scripts/render-skill-index.py docs/skills-index.md")
    lines.append("> ```")
    lines.append("")

    by_kind: Dict[str, List[Tuple[str, Dict, pathlib.Path]]] = {}
    for kind, name, fm, path in entries:
        by_kind.setdefault(kind, []).append((name, fm, path))

    kinds_order = [("agent", "Agents"), ("skill", "Skills"), ("command", "Commands")]
    for kind, heading in kinds_order:
        rows = by_kind.get(kind, [])
        lines.append(f"## {heading} ({len(rows)})")
        lines.append("")
        lines.append("| Name | Description | Version | Requires | Model / Tools | File |")
        lines.append("|------|-------------|---------|----------|---------------|------|")
        for name, fm, path in rows:
            desc = flatten_desc(fm.get("description"))
            if len(desc) > 160:
                desc = desc[:157] + "…"
            version = fm.get("version", "-")
            requires = fmt_requires(fm.get("requires"))
            model = fm.get("model") or fm.get("allowed-tools") or "-"
            rel = path.relative_to(ROOT)
            lines.append(
                f"| `{name}` | {desc} | `{version}` | {requires} | `{model}` | `{rel}` |"
            )
        lines.append("")

    lines.append("---")
    lines.append("")
    total = sum(len(v) for v in by_kind.values())
    lines.append(f"Total: **{total}** entries "
                 f"({len(by_kind.get('agent', []))} agents, "
                 f"{len(by_kind.get('skill', []))} skills, "
                 f"{len(by_kind.get('command', []))} commands).")
    lines.append("")
    return "\n".join(lines)


def main(argv: List[str]) -> int:
    entries = collect()
    out = render(entries)
    if len(argv) > 1:
        target = pathlib.Path(argv[1])
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(out)
        sys.stderr.write(f"Wrote {target} ({len(out)} bytes, {len(entries)} entries)\n")
    else:
        sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
